plugins { id 'com.android.application' }

android {
    namespace 'com.cloudstorageexplorer.app'
    compileSdk 35
    defaultConfig {
        applicationId 'com.cloudstorageexplorer.app'
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName '1.1'
    }
}

dependencies {
    implementation 'androidx.documentfile:documentfile:1.1.0'
}
