package com.cloudexplorer.finalapp;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.view.*;import android.widget.*;import androidx.core.content.FileProvider;
import java.io.*;import java.nio.charset.StandardCharsets;import java.text.*;import java.util.*;import java.util.zip.*;

public class MainActivity extends Activity {
    static final int PICK_TREE=10,PICK_FILE=11; LinearLayout root,list; TextView path,status; Uri currentTree; File currentDir; final ArrayList<File> items=new ArrayList<>(); ArrayList<File> selected=new ArrayList<>(); SharedPreferences prefs; String sort="name"; boolean foldersFirst=true; Uri pendingDest;
    @Override public void onCreate(Bundle b){super.onCreate(b); prefs=getSharedPreferences("state",0); buildUI(); showHome();}
    TextView tv(String s,int sp){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(Color.DKGRAY);t.setPadding(18,12,18,12);return t;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setMinHeight(56);return b;}
    void buildUI(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);setContentView(root); LinearLayout bar=new LinearLayout(this);bar.setHorizontalScrollBarEnabled(true);String[] bs={"☰","←","→","⟳","Select","Copy","Cut","Paste","Delete","Rename","Share","ZIP","Properties","Search","Cloud +","Sort","Favorites"}; for(String s:bs){Button b=btn(s);bar.addView(b,new LinearLayout.LayoutParams(-2,-2)); b.setOnClickListener(v->action(s));} root.addView(new HorizontalScrollView(this){{addView(bar);}},new LinearLayout.LayoutParams(-1,-2)); path=tv("Cloud Explorer",18);root.addView(path);status=tv("",14);root.addView(status);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(new ScrollView(this){{addView(list);}},new LinearLayout.LayoutParams(-1,0,1));}
    void showHome(){currentDir=null;currentTree=null;path.setText("Storage & Cloud");list.removeAllViews();addRow("📱 Internal Storage",()->openRoot(Environment.getExternalStorageDirectory()));File[] roots=Environment.getExternalStorageDirectory().getParentFile().listFiles(); if(roots!=null)for(File f:roots)if(f.isDirectory()&&!f.getName().equals("emulated"))addRow("💾 "+f.getName(),()->openRoot(f)); addRow("☁️ Add Cloud Storage",()->pickTree()); addRow("⭐ Favorites",this::favorites);}
    void openRoot(File f){currentDir=f;refresh();}
    void refresh(){list.removeAllViews(); if(currentDir==null){showHome();return;}path.setText(currentDir.getAbsolutePath()); File[] a=currentDir.listFiles();items.clear();if(a!=null)items.addAll(Arrays.asList(a));sortItems(); for(File f:items)addFileRow(f); status.setText(items.size()+" items • "+human(currentDir.getFreeSpace())+" free / "+human(currentDir.getTotalSpace()));}
    void sortItems(){Collections.sort(items,(a,b)->{if(foldersFirst&&a.isDirectory()!=b.isDirectory())return a.isDirectory()?-1:1;int c; if(sort.equals("size"))c=Long.compare(a.length(),b.length());else if(sort.equals("date"))c=Long.compare(a.lastModified(),b.lastModified());else if(sort.equals("type"))c=ext(a).compareToIgnoreCase(ext(b));else c=a.getName().compareToIgnoreCase(b.getName());return c;});}
    void addFileRow(File f){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);TextView n=tv((f.isDirectory()?"📁 ":icon(f)+" ")+f.getName(),17);r.addView(n,new LinearLayout.LayoutParams(0,-2,1));TextView z=tv(f.isDirectory()?"Folder":human(f.length()),13);r.addView(z);r.setOnClickListener(v->{if(f.isDirectory())openRoot(f);else selectOne(f);});r.setOnLongClickListener(v->{selectOne(f);return true;});list.addView(r);}
    void selectOne(File f){selected.clear();selected.add(f);status.setText("Selected: "+f.getName());}
    void action(String s){try{switch(s){case"☰":showHome();break;case"←":if(currentDir!=null){File p=currentDir.getParentFile();if(p!=null)openRoot(p);else showHome();}break;case"⟳":refresh();break;case"Select":selectMode();break;case"Copy":copy(false);break;case"Cut":copy(true);break;case"Paste":paste();break;case"Delete":deleteSelected();break;case"Rename":rename();break;case"Share":share();break;case"ZIP":zipSelected();break;case"Properties":properties();break;case"Search":search();break;case"Cloud +":pickTree();break;case"Sort":chooseSort();break;case"Favorites":favorites();break;}}catch(Exception e){toast(e.getMessage());}}
    void selectMode(){selected.clear();list.removeAllViews();if(currentDir!=null)for(File f:items){CheckBox c=new CheckBox(this);c.setText((f.isDirectory()?"📁 ":icon(f)+" ")+f.getName());c.setTextSize(17);c.setPadding(12,12,12,12);c.setOnCheckedChangeListener((b,x)->{if(x)selected.add(f);else selected.remove(f);});list.addView(c);}status.setText("Select files, then use Copy/Cut/Delete/ZIP/Share");}
    void copy(boolean cut){if(selected.isEmpty()){toast("Select files first");return;}String p=join(selected);prefs.edit().putString("clipboard",p).putBoolean("cut",cut).apply();status.setText((cut?"Cut":"Copied")+" "+selected.size()+" item(s)");}
    void paste(){String p=prefs.getString("clipboard","");if(p.isEmpty()||currentDir==null){toast("Nothing to paste");return;}for(String q:p.split("\\n"))if(!q.isEmpty())try{File src=new File(q),dst=new File(currentDir,src.getName());copyRec(src,dst);}catch(Exception e){toast(e.getMessage());}if(prefs.getBoolean("cut",false))prefs.edit().remove("clipboard").apply();refresh();}
    void copyRec(File s,File d)throws IOException{if(s.isDirectory()){if(!d.exists()&&!d.mkdirs())throw new IOException("Cannot create folder");File[] x=s.listFiles();if(x!=null)for(File f:x)copyRec(f,new File(d,f.getName()));}else{try(InputStream in=new FileInputStream(s);OutputStream out=new FileOutputStream(d)){byte[] b=new byte[8192];int n;while((n=in.read(b))>0)out.write(b,0,n);}}}
    void deleteSelected(){if(selected.isEmpty())return;new AlertDialog.Builder(this).setTitle("Delete").setMessage("Delete "+selected.size()+" item(s)?").setPositiveButton("Delete",(d,w)->{for(File f:selected)del(f);selected.clear();refresh();}).setNegativeButton("Cancel",null).show();}
    boolean del(File f){if(f.isDirectory()){File[] x=f.listFiles();if(x!=null)for(File c:x)del(c);}return f.delete();}
    void rename(){if(selected.size()!=1){toast("Select one item");return;}File f=selected.get(0);EditText e=new EditText(this);e.setText(f.getName());new AlertDialog.Builder(this).setTitle("Rename").setView(e).setPositiveButton("Rename",(d,w)->{String n=e.getText().toString().trim();if(!n.isEmpty())f.renameTo(new File(f.getParentFile(),n));refresh();}).setNegativeButton("Cancel",null).show();}
    void share(){if(selected.isEmpty()){toast("Select files first");return;}Intent i=new Intent(Intent.ACTION_SEND_MULTIPLE);i.setType("*/*");ArrayList<Uri> us=new ArrayList<>();for(File f:selected){try{File c=new File(getCacheDir(),f.getName());copyRec(f,c);us.add(FileProvider.getUriForFile(this,getPackageName()+".files",c));}catch(Exception e){}}i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);i.putParcelableArrayListExtra(Intent.EXTRA_STREAM,us);try{startActivity(Intent.createChooser(i,"Share files"));}catch(Exception e){toast("Share provider unavailable");}}
    void zipSelected(){if(selected.isEmpty()||currentDir==null){toast("Select files first");return;}File out=new File(currentDir,"Archive_"+new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date())+".zip");try(ZipOutputStream z=new ZipOutputStream(new FileOutputStream(out))){for(File f:selected)zipAdd(z,f,f.getName());toast("ZIP created");refresh();}catch(Exception e){toast(e.getMessage());}}
    void zipAdd(ZipOutputStream z,File f,String name)throws IOException{if(f.isDirectory()){z.putNextEntry(new ZipEntry(name+"/"));z.closeEntry();File[] x=f.listFiles();if(x!=null)for(File c:x)zipAdd(z,c,name+"/"+c.getName());}else{z.putNextEntry(new ZipEntry(name));try(FileInputStream in=new FileInputStream(f)){byte[] b=new byte[8192];int n;while((n=in.read(b))>0)z.write(b,0,n);}z.closeEntry();}}
    void properties(){if(selected.size()!=1){toast("Select one item");return;}File f=selected.get(0);String s="Name: "+f.getName()+"\nType: "+ext(f)+"\nSize: "+human(f.length())+"\nPath: "+f.getAbsolutePath()+"\nModified: "+new Date(f.lastModified())+"\nFolder: "+f.isDirectory();new AlertDialog.Builder(this).setTitle("Properties").setMessage(s).setPositiveButton("OK",null).setNeutralButton("Copy text",(d,w)->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(android.content.ClipData.newPlainText("Properties",s));}).show();}
    void search(){if(currentDir==null)return;EditText e=new EditText(this);e.setHint("File or folder name");new AlertDialog.Builder(this).setTitle("Search").setView(e).setPositiveButton("Search",(d,w)->{String q=e.getText().toString().toLowerCase();list.removeAllViews();for(File f:items)if(f.getName().toLowerCase().contains(q))addFileRow(f);}).setNegativeButton("Cancel",null).show();}
    void chooseSort(){String[] x={"Name","Type / Extension","Size","Modified date"};new AlertDialog.Builder(this).setTitle("Sort").setItems(x,(d,w)->{sort=w==0?"name":w==1?"type":w==2?"size":"date";refresh();});}
    void favorites(){list.removeAllViews();path.setText("Favorites");String raw=prefs.getString("favorites","");for(String p:raw.split("\\n"))if(!p.isEmpty()){File f=new File(p);if(f.exists())addRow("⭐ "+f.getName(),()->{selected.clear();selected.add(f);status.setText("Selected favorite: "+f.getName());});}}
    void addRow(String s,final Runnable r){TextView t=tv(s,18);t.setOnClickListener(v->r.run());list.addView(t);}
    void pickTree(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,PICK_TREE);}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null)return;if(r==PICK_TREE){Uri u=d.getData();try{getContentResolver().takePersistableUriPermission(u,d.getFlags()&(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION));}catch(Exception ignored){}prefs.edit().putString("cloud_"+System.currentTimeMillis(),u.toString()).apply();toast("Storage / Cloud added");showHome();}}
    String join(ArrayList<File>x){StringBuilder b=new StringBuilder();for(File f:x)b.append(f.getAbsolutePath()).append('\n');return b.toString();}
    String ext(File f){String n=f.getName();int p=n.lastIndexOf('.');return p>0?n.substring(p+1):"";}
    String icon(File f){String e=ext(f).toLowerCase();if(e.matches("jpg|jpeg|png|gif|webp"))return"🖼️";if(e.matches("mp4|mkv|avi|mov"))return"🎬";if(e.matches("mp3|wav|flac|aac"))return"🎵";if(e.matches("zip|7z|rar"))return"🗜️";if(e.matches("pdf"))return"📕";if(e.matches("apk|xapk|apks|aab"))return"📦";return"📄";}
    String human(long n){if(n<1024)return n+" B";double x=n;String[]u={"KB","MB","GB","TB"};int i=0;while(x>=1024&&i<u.length-1){x/=1024;i++;}return String.format(Locale.US,"%.1f %s",x,u[i]);}
    void toast(String s){Toast.makeText(this,s==null?"Error":s,Toast.LENGTH_LONG).show();}
}
